/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author fer
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        this.setTitle("Login");
        this.panelLogin.setVisible(true);
        this.panelAdmin.setVisible(false);
        this.panelEmple.setVisible(false);
        this.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        txtUserLogin = new org.edisoncor.gui.textField.TextField();
        btnAceptLogin = new org.edisoncor.gui.button.ButtonSeven();
        btnSalirLogin = new org.edisoncor.gui.button.ButtonSeven();
        txtPassLogin = new org.edisoncor.gui.passwordField.PasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelAdmin = new javax.swing.JPanel();
        tabbedPaneHeader = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        paneUsuarios = new org.edisoncor.gui.panel.Panel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        txtTipoUser = new org.edisoncor.gui.textField.TextFieldRound();
        txtEmailUser = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtPassUser = new org.edisoncor.gui.textField.TextFieldRound();
        btnAddUser = new org.edisoncor.gui.button.ButtonAction();
        btnModUser = new org.edisoncor.gui.button.ButtonAction();
        btnDeletUser = new org.edisoncor.gui.button.ButtonAction();
        jLabel3 = new javax.swing.JLabel();
        paneHorariosAdmin = new org.edisoncor.gui.panel.Panel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtDniTarea = new org.edisoncor.gui.comboBox.ComboBoxRectIcon();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txtIdTarea = new org.edisoncor.gui.textField.TextFieldRound();
        txtFechaTarea = new org.edisoncor.gui.textField.TextFieldRound();
        txtZonaTarea = new org.edisoncor.gui.textField.TextFieldRound();
        txtTramoHorario = new org.edisoncor.gui.textField.TextFieldRound();
        txtTarea = new org.edisoncor.gui.textField.TextFieldRound();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaHorarios = new javax.swing.JTable();
        btnAddTarea = new org.edisoncor.gui.button.ButtonAction();
        btnModTarea = new org.edisoncor.gui.button.ButtonAction();
        btnDeletTarea = new org.edisoncor.gui.button.ButtonAction();
        paneIncidenAdmin = new org.edisoncor.gui.panel.Panel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaIncidencias = new javax.swing.JTable();
        txtCodIncidencia = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtNomIncidencia = new org.edisoncor.gui.textField.TextFieldRound();
        txtTipoIncidencia = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtDescripcionIncide = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel49 = new javax.swing.JLabel();
        txtLocalizacionInciden = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel50 = new javax.swing.JLabel();
        txtEstadoInciden = new org.edisoncor.gui.textField.TextFieldRound();
        txtPrioridadIncide = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btnAddInciden = new org.edisoncor.gui.button.ButtonAction();
        btnModInciden = new org.edisoncor.gui.button.ButtonAction();
        btnDeletIncide = new org.edisoncor.gui.button.ButtonAction();
        cbEmpleIncidencias = new org.edisoncor.gui.comboBox.ComboBoxRound();
        btnInformeIncidencia = new org.edisoncor.gui.button.ButtonAction();
        btnAddFotoAdmin = new org.edisoncor.gui.button.ButtonRound();
        paneEmpleadosAdmin = new org.edisoncor.gui.panel.Panel();
        btnDeletEmple = new org.edisoncor.gui.button.ButtonAction();
        btnModEmple = new org.edisoncor.gui.button.ButtonAction();
        btnAddEmple = new org.edisoncor.gui.button.ButtonAction();
        jLabel35 = new javax.swing.JLabel();
        txtEmailEmple = new org.edisoncor.gui.textField.TextFieldRound();
        txtTlfnoEmple = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtPuestoEmple = new org.edisoncor.gui.textField.TextFieldRound();
        txtApeEmple = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtNomEmple = new org.edisoncor.gui.textField.TextFieldRound();
        txtDniEmple = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        txtBusqEmpleado = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel41 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        panelEmple = new javax.swing.JPanel();
        tabbedPaneHeader3 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        paneHorarioEmple = new org.edisoncor.gui.panel.Panel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        cbDniTareas = new org.edisoncor.gui.comboBox.ComboBoxRectIcon();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        txtIdTareas = new org.edisoncor.gui.textField.TextFieldRound();
        txtFechaTareas = new org.edisoncor.gui.textField.TextFieldRound();
        txtZonaTareas = new org.edisoncor.gui.textField.TextFieldRound();
        txtTramoHorarios = new org.edisoncor.gui.textField.TextFieldRound();
        txtTareas = new org.edisoncor.gui.textField.TextFieldRound();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();
        txtAddTareas = new org.edisoncor.gui.button.ButtonAction();
        btnModTareas = new org.edisoncor.gui.button.ButtonAction();
        txtDeletTareas = new org.edisoncor.gui.button.ButtonAction();
        paneIncidenEmple = new org.edisoncor.gui.panel.Panel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablaIncidencias2 = new javax.swing.JTable();
        txtCodIncidencias = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txtNomIncidencias = new org.edisoncor.gui.textField.TextFieldRound();
        txtTipoIncidencias = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtDescripcionIncideas = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel73 = new javax.swing.JLabel();
        txtLocalizacionIncidencias = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel74 = new javax.swing.JLabel();
        txtEstadoIncidencias = new org.edisoncor.gui.textField.TextFieldRound();
        txtPrioridadIncidencias = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        btnAddIncidencias = new org.edisoncor.gui.button.ButtonAction();
        btnModIncidencias = new org.edisoncor.gui.button.ButtonAction();
        btnDeletIncidencias = new org.edisoncor.gui.button.ButtonAction();
        cbIncidenEmple = new org.edisoncor.gui.comboBox.ComboBoxRound();
        btnInformeIncidencias = new org.edisoncor.gui.button.ButtonAction();
        btnAddFotoEmple = new org.edisoncor.gui.button.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelLogin.add(txtUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 190, -1));

        btnAceptLogin.setText("Ingresar");
        panelLogin.add(btnAceptLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, -1));

        btnSalirLogin.setText("Salir");
        panelLogin.add(btnSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 100, -1));

        txtPassLogin.setText("passwordField1");
        panelLogin.add(txtPassLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Usuario:");
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pass:");
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        panelAdmin.setPreferredSize(new java.awt.Dimension(1070, 607));

        paneUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaUsuarios);

        paneUsuarios.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 420, 524));
        paneUsuarios.add(txtTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 46, 333, -1));
        paneUsuarios.add(txtEmailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 89, 333, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Usuario:");
        paneUsuarios.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 90, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Tipo:");
        paneUsuarios.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 47, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Pass:");
        paneUsuarios.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 141, -1, -1));
        paneUsuarios.add(txtPassUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 140, 333, -1));

        btnAddUser.setText("INSERTAR");
        paneUsuarios.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 130, -1));

        btnModUser.setText("MODIFICAR");
        paneUsuarios.add(btnModUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 130, -1));

        btnDeletUser.setText("ELIMINAR");
        paneUsuarios.add(btnDeletUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N
        paneUsuarios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 220, 260));

        tabbedPaneHeader.addTab("Admin", paneUsuarios);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Id Tarea:");

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Fecha:");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Dni:");

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Zona:");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Tramo Horario:");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Tarea:");

        txtTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTareaActionPerformed(evt);
            }
        });

        tablaHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tablaHorarios);

        btnAddTarea.setText("AGREGAR");

        btnModTarea.setText("MODIFICAR");

        btnDeletTarea.setText("BORRAR");
        btnDeletTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletTareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneHorariosAdminLayout = new javax.swing.GroupLayout(paneHorariosAdmin);
        paneHorariosAdmin.setLayout(paneHorariosAdminLayout);
        paneHorariosAdminLayout.setHorizontalGroup(
            paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHorariosAdminLayout.createSequentialGroup()
                .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneHorariosAdminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneHorariosAdminLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addComponent(jLabel55))
                        .addGap(18, 18, 18)
                        .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtIdTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel56)
                            .addComponent(jLabel57))
                        .addGap(26, 26, 26)
                        .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDniTarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZonaTarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHorariosAdminLayout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addGap(30, 30, 30)
                                .addComponent(txtTramoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHorariosAdminLayout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addGap(67, 67, 67)
                                .addComponent(txtTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(102, 102, 102))
            .addGroup(paneHorariosAdminLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnModTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnDeletTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneHorariosAdminLayout.setVerticalGroup(
            paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHorariosAdminLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(txtDniTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel58)
                    .addComponent(txtIdTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTramoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jLabel57)
                    .addComponent(jLabel59)
                    .addComponent(txtFechaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZonaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneHorariosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabbedPaneHeader.addTab("Horarios", paneHorariosAdmin);

        tablaIncidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tablaIncidencias);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Codigo:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Nombre:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Tipo:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Seleccione foto:");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Fecha Suceso:");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Fecha Resolución:");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Descripción:");

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Localización:");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Estado:");

        txtPrioridadIncide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrioridadIncideActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Prioridad:");

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Empleado:");

        btnAddInciden.setText("INSERTAR");

        btnModInciden.setText("MODIFICAR");

        btnDeletIncide.setText("ELIMINAR");

        btnInformeIncidencia.setText("INFORMES");

        btnAddFotoAdmin.setText("AÑADIR...");

        javax.swing.GroupLayout paneIncidenAdminLayout = new javax.swing.GroupLayout(paneIncidenAdmin);
        paneIncidenAdmin.setLayout(paneIncidenAdminLayout);
        paneIncidenAdminLayout.setHorizontalGroup(
            paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                            .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                                    .addGap(623, 623, 623)
                                    .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel42)
                                        .addComponent(jLabel43))
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(jLabel44)
                                    .addGap(44, 44, 44)))
                            .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                                    .addComponent(jLabel52)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbEmpleIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                                    .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel51)
                                        .addComponent(jLabel50))
                                    .addGap(45, 45, 45)
                                    .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDescripcionIncide, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addComponent(txtLocalizacionInciden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEstadoInciden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(txtPrioridadIncide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                        .addGap(592, 592, 592)
                        .addComponent(btnAddInciden, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnModInciden, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletIncide, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInformeIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel48))
                        .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(337, 337, 337))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(363, 363, 363)))
                        .addComponent(jLabel46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddFotoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
            .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(497, Short.MAX_VALUE)))
        );
        paneIncidenAdminLayout.setVerticalGroup(
            paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenAdminLayout.createSequentialGroup()
                .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addGap(23, 23, 23)
                        .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(txtNomIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))))
                .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(btnAddFotoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addGap(27, 27, 27)
                .addComponent(jLabel47)
                .addGap(27, 27, 27)
                .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionIncide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGap(34, 34, 34)
                        .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(txtEstadoInciden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrioridadIncide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51))
                        .addGap(29, 29, 29)
                        .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(cbEmpleIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddInciden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModInciden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeletIncide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInformeIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                        .addComponent(txtLocalizacionInciden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(paneIncidenAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneIncidenAdminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7)
                    .addContainerGap()))
        );

        tabbedPaneHeader.addTab("Incidencias", paneIncidenAdmin);

        paneEmpleadosAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeletEmple.setText("ELIMINAR");
        paneEmpleadosAdmin.add(btnDeletEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 220, -1));

        btnModEmple.setText("MODIFICAR");
        paneEmpleadosAdmin.add(btnModEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 220, -1));

        btnAddEmple.setText("INSERTAR");
        paneEmpleadosAdmin.add(btnAddEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 220, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Email:");
        paneEmpleadosAdmin.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));
        paneEmpleadosAdmin.add(txtEmailEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 240, -1));
        paneEmpleadosAdmin.add(txtTlfnoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 240, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Tlfno:");
        paneEmpleadosAdmin.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Puesto:");
        paneEmpleadosAdmin.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));
        paneEmpleadosAdmin.add(txtPuestoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 240, -1));
        paneEmpleadosAdmin.add(txtApeEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 240, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Apellidos:");
        paneEmpleadosAdmin.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Nombre:");
        paneEmpleadosAdmin.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));
        paneEmpleadosAdmin.add(txtNomEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 240, -1));
        paneEmpleadosAdmin.add(txtDniEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 240, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Dni:");
        paneEmpleadosAdmin.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tablaEmpleados);

        paneEmpleadosAdmin.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 470, 480));
        paneEmpleadosAdmin.add(txtBusqEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 240, -1));

        jLabel41.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Buscar:");
        paneEmpleadosAdmin.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        paneEmpleadosAdmin.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 240, 250));

        tabbedPaneHeader.addTab("Empleados", paneEmpleadosAdmin);

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
            .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabbedPaneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
            .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabbedPaneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEmple.setPreferredSize(new java.awt.Dimension(1070, 607));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Id Tarea:");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Fecha:");

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Dni:");

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Zona:");

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Tramo Horario:");

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Tarea:");

        txtZonaTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZonaTareasActionPerformed(evt);
            }
        });

        txtTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTareasActionPerformed(evt);
            }
        });

        tablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tablaTareas);

        txtAddTareas.setText("AGREGAR");

        btnModTareas.setText("MODIFICAR");

        txtDeletTareas.setText("BORRAR");

        javax.swing.GroupLayout paneHorarioEmpleLayout = new javax.swing.GroupLayout(paneHorarioEmple);
        paneHorarioEmple.setLayout(paneHorarioEmpleLayout);
        paneHorarioEmpleLayout.setHorizontalGroup(
            paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHorarioEmpleLayout.createSequentialGroup()
                .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneHorarioEmpleLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneHorarioEmpleLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60)
                            .addComponent(jLabel61))
                        .addGap(18, 18, 18)
                        .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtIdTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel62)
                            .addComponent(jLabel63))
                        .addGap(26, 26, 26)
                        .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDniTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZonaTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHorarioEmpleLayout.createSequentialGroup()
                                .addComponent(jLabel64)
                                .addGap(30, 30, 30)
                                .addComponent(txtTramoHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHorarioEmpleLayout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addGap(67, 67, 67)
                                .addComponent(txtTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(102, 102, 102))
            .addGroup(paneHorarioEmpleLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnModTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(txtAddTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(txtDeletTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneHorarioEmpleLayout.setVerticalGroup(
            paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHorarioEmpleLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(cbDniTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel64)
                    .addComponent(txtIdTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTramoHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jLabel63)
                    .addComponent(jLabel65)
                    .addComponent(txtFechaTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZonaTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneHorarioEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeletTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabbedPaneHeader3.addTab("Horarios", paneHorarioEmple);

        tablaIncidencias2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tablaIncidencias2);

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Codigo:");

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Nombre:");

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Tipo:");

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Seleccione foto:");

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Fecha Suceso:");

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Fecha Resolución:");

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Descripción:");

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Localización:");

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Estado:");

        txtPrioridadIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrioridadIncidenciasActionPerformed(evt);
            }
        });

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Prioridad:");

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Empleado:");

        btnAddIncidencias.setText("INSERTAR");

        btnModIncidencias.setText("MODIFICAR");

        btnDeletIncidencias.setText("ELIMINAR");

        btnInformeIncidencias.setText("INFORMES");

        btnAddFotoEmple.setText("AÑADIR..");

        javax.swing.GroupLayout paneIncidenEmpleLayout = new javax.swing.GroupLayout(paneIncidenEmple);
        paneIncidenEmple.setLayout(paneIncidenEmpleLayout);
        paneIncidenEmpleLayout.setHorizontalGroup(
            paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel72))
                    .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createSequentialGroup()
                            .addComponent(jLabel71)
                            .addGap(337, 337, 337))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createSequentialGroup()
                            .addComponent(jLabel73)
                            .addGap(363, 363, 363)))))
            .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                            .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                                    .addGap(623, 623, 623)
                                    .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel66)
                                        .addComponent(jLabel67))
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createSequentialGroup()
                                            .addComponent(jLabel68)
                                            .addGap(44, 44, 44))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createSequentialGroup()
                                            .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel70)
                                                .addComponent(jLabel69))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                            .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(txtCodIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(txtTipoIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(btnAddFotoEmple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                                    .addComponent(jLabel76)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbIncidenEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                                    .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel75)
                                        .addComponent(jLabel74))
                                    .addGap(45, 45, 45)
                                    .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDescripcionIncideas, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addComponent(txtLocalizacionIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEstadoIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(txtPrioridadIncidencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                        .addGap(592, 592, 592)
                        .addComponent(btnAddIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnModIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInformeIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(497, Short.MAX_VALUE)))
        );
        paneIncidenEmpleLayout.setVerticalGroup(
            paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIncidenEmpleLayout.createSequentialGroup()
                .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel66))
                        .addGap(23, 23, 23)
                        .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(txtNomIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel68))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(btnAddFotoEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel70)
                .addGap(26, 26, 26)
                .addComponent(jLabel71)
                .addGap(27, 27, 27)
                .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionIncideas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                        .addComponent(jLabel73)
                        .addGap(34, 34, 34)
                        .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel74)
                            .addComponent(txtEstadoIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrioridadIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel75))
                        .addGap(29, 29, 29)
                        .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel76)
                            .addComponent(cbIncidenEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeletIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInformeIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                        .addComponent(txtLocalizacionIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(paneIncidenEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneIncidenEmpleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane10)
                    .addContainerGap()))
        );

        tabbedPaneHeader3.addTab("Incidencias", paneIncidenEmple);

        javax.swing.GroupLayout panelEmpleLayout = new javax.swing.GroupLayout(panelEmple);
        panelEmple.setLayout(panelEmpleLayout);
        panelEmpleLayout.setHorizontalGroup(
            panelEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneHeader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEmpleLayout.setVerticalGroup(
            panelEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneHeader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrioridadIncideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrioridadIncideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrioridadIncideActionPerformed

    private void txtTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTareaActionPerformed

    private void txtTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTareasActionPerformed

    private void txtPrioridadIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrioridadIncidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrioridadIncidenciasActionPerformed

    private void txtZonaTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZonaTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZonaTareasActionPerformed

    private void btnDeletTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.edisoncor.gui.button.ButtonSeven btnAceptLogin;
    public org.edisoncor.gui.button.ButtonAction btnAddEmple;
    public org.edisoncor.gui.button.ButtonRound btnAddFotoAdmin;
    public org.edisoncor.gui.button.ButtonRound btnAddFotoEmple;
    public org.edisoncor.gui.button.ButtonAction btnAddInciden;
    public org.edisoncor.gui.button.ButtonAction btnAddIncidencias;
    public org.edisoncor.gui.button.ButtonAction btnAddTarea;
    public org.edisoncor.gui.button.ButtonAction btnAddUser;
    public org.edisoncor.gui.button.ButtonAction btnDeletEmple;
    public org.edisoncor.gui.button.ButtonAction btnDeletIncide;
    public org.edisoncor.gui.button.ButtonAction btnDeletIncidencias;
    public org.edisoncor.gui.button.ButtonAction btnDeletTarea;
    public org.edisoncor.gui.button.ButtonAction btnDeletUser;
    public org.edisoncor.gui.button.ButtonAction btnInformeIncidencia;
    public org.edisoncor.gui.button.ButtonAction btnInformeIncidencias;
    public org.edisoncor.gui.button.ButtonAction btnModEmple;
    public org.edisoncor.gui.button.ButtonAction btnModInciden;
    public org.edisoncor.gui.button.ButtonAction btnModIncidencias;
    public org.edisoncor.gui.button.ButtonAction btnModTarea;
    public org.edisoncor.gui.button.ButtonAction btnModTareas;
    public org.edisoncor.gui.button.ButtonAction btnModUser;
    public org.edisoncor.gui.button.ButtonSeven btnSalirLogin;
    public org.edisoncor.gui.comboBox.ComboBoxRectIcon cbDniTareas;
    public org.edisoncor.gui.comboBox.ComboBoxRound cbEmpleIncidencias;
    public org.edisoncor.gui.comboBox.ComboBoxRound cbIncidenEmple;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    public javax.swing.JLabel jLabel40;
    public javax.swing.JLabel jLabel41;
    public javax.swing.JLabel jLabel42;
    public javax.swing.JLabel jLabel43;
    public javax.swing.JLabel jLabel44;
    public javax.swing.JLabel jLabel45;
    public javax.swing.JLabel jLabel46;
    public javax.swing.JLabel jLabel47;
    public javax.swing.JLabel jLabel48;
    public javax.swing.JLabel jLabel49;
    public javax.swing.JLabel jLabel50;
    public javax.swing.JLabel jLabel51;
    public javax.swing.JLabel jLabel52;
    public javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel54;
    public javax.swing.JLabel jLabel55;
    public javax.swing.JLabel jLabel56;
    public javax.swing.JLabel jLabel57;
    public javax.swing.JLabel jLabel58;
    public javax.swing.JLabel jLabel59;
    public javax.swing.JLabel jLabel60;
    public javax.swing.JLabel jLabel61;
    public javax.swing.JLabel jLabel62;
    public javax.swing.JLabel jLabel63;
    public javax.swing.JLabel jLabel64;
    public javax.swing.JLabel jLabel65;
    public javax.swing.JLabel jLabel66;
    public javax.swing.JLabel jLabel67;
    public javax.swing.JLabel jLabel68;
    public javax.swing.JLabel jLabel69;
    public javax.swing.JLabel jLabel70;
    public javax.swing.JLabel jLabel71;
    public javax.swing.JLabel jLabel72;
    public javax.swing.JLabel jLabel73;
    public javax.swing.JLabel jLabel74;
    public javax.swing.JLabel jLabel75;
    public javax.swing.JLabel jLabel76;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public org.edisoncor.gui.panel.Panel paneEmpleadosAdmin;
    public org.edisoncor.gui.panel.Panel paneHorarioEmple;
    public org.edisoncor.gui.panel.Panel paneHorariosAdmin;
    public org.edisoncor.gui.panel.Panel paneIncidenAdmin;
    public org.edisoncor.gui.panel.Panel paneIncidenEmple;
    public org.edisoncor.gui.panel.Panel paneUsuarios;
    public javax.swing.JPanel panelAdmin;
    public javax.swing.JPanel panelEmple;
    public javax.swing.JPanel panelLogin;
    public org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader;
    public org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader3;
    public javax.swing.JTable tablaEmpleados;
    public javax.swing.JTable tablaHorarios;
    public javax.swing.JTable tablaIncidencias;
    public javax.swing.JTable tablaIncidencias2;
    public javax.swing.JTable tablaTareas;
    public javax.swing.JTable tablaUsuarios;
    public org.edisoncor.gui.button.ButtonAction txtAddTareas;
    public org.edisoncor.gui.textField.TextFieldRound txtApeEmple;
    public org.edisoncor.gui.textField.TextFieldRound txtBusqEmpleado;
    public org.edisoncor.gui.textField.TextFieldRound txtCodIncidencia;
    public org.edisoncor.gui.textField.TextFieldRound txtCodIncidencias;
    public org.edisoncor.gui.button.ButtonAction txtDeletTareas;
    public org.edisoncor.gui.textField.TextFieldRound txtDescripcionIncide;
    public org.edisoncor.gui.textField.TextFieldRound txtDescripcionIncideas;
    public org.edisoncor.gui.textField.TextFieldRound txtDniEmple;
    public org.edisoncor.gui.comboBox.ComboBoxRectIcon txtDniTarea;
    public org.edisoncor.gui.textField.TextFieldRound txtEmailEmple;
    public org.edisoncor.gui.textField.TextFieldRound txtEmailUser;
    public org.edisoncor.gui.textField.TextFieldRound txtEstadoInciden;
    public org.edisoncor.gui.textField.TextFieldRound txtEstadoIncidencias;
    public org.edisoncor.gui.textField.TextFieldRound txtFechaTarea;
    public org.edisoncor.gui.textField.TextFieldRound txtFechaTareas;
    public org.edisoncor.gui.textField.TextFieldRound txtIdTarea;
    public org.edisoncor.gui.textField.TextFieldRound txtIdTareas;
    public org.edisoncor.gui.textField.TextFieldRound txtLocalizacionInciden;
    public org.edisoncor.gui.textField.TextFieldRound txtLocalizacionIncidencias;
    public org.edisoncor.gui.textField.TextFieldRound txtNomEmple;
    public org.edisoncor.gui.textField.TextFieldRound txtNomIncidencia;
    public org.edisoncor.gui.textField.TextFieldRound txtNomIncidencias;
    public org.edisoncor.gui.passwordField.PasswordField txtPassLogin;
    public org.edisoncor.gui.textField.TextFieldRound txtPassUser;
    public org.edisoncor.gui.textField.TextFieldRound txtPrioridadIncide;
    public org.edisoncor.gui.textField.TextFieldRound txtPrioridadIncidencias;
    public org.edisoncor.gui.textField.TextFieldRound txtPuestoEmple;
    public org.edisoncor.gui.textField.TextFieldRound txtTarea;
    public org.edisoncor.gui.textField.TextFieldRound txtTareas;
    public org.edisoncor.gui.textField.TextFieldRound txtTipoIncidencia;
    public org.edisoncor.gui.textField.TextFieldRound txtTipoIncidencias;
    public org.edisoncor.gui.textField.TextFieldRound txtTipoUser;
    public org.edisoncor.gui.textField.TextFieldRound txtTlfnoEmple;
    public org.edisoncor.gui.textField.TextFieldRound txtTramoHorario;
    public org.edisoncor.gui.textField.TextFieldRound txtTramoHorarios;
    public org.edisoncor.gui.textField.TextField txtUserLogin;
    public org.edisoncor.gui.textField.TextFieldRound txtZonaTarea;
    public org.edisoncor.gui.textField.TextFieldRound txtZonaTareas;
    // End of variables declaration//GEN-END:variables
}
